name: dart_midi_message
description: A library for parsing and creating MIDI messages.
version: 1.0.0

environment:
  sdk: ^3.5.1

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
